name: hotgists
favicon: null
layout_spectrum: 0.3588035088032484
typography_spectrum: 0.1966386386193335
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.24306433973833919
  lightness: 0.3763300778809935
  saturation: 0.2519601881504059
  rhythmicContrast: 0.8183852885849774
purpose: []
